<?php

namespace App\Services\Google;

use App\Models\GoogleConnection;
use Google\Service\Calendar;
use Google\Service\Calendar\CalendarListEntry;
use Google\Service\Calendar\Event;
use Google\Service\Calendar\EventDateTime;
use Illuminate\Support\Collection;
use Illuminate\Support\Facades\Config;

class GoogleCalendarService
{
    public function __construct(private readonly GoogleClientFactory $clientFactory)
    {
    }

    public function listEvents(GoogleConnection $connection, string $calendarId, \DateTimeInterface $from, \DateTimeInterface $to): Collection
    {
        $client = $this->clientFactory->buildClient($connection);
        $service = new Calendar($client);
        $events = $service->events->listEvents($calendarId, [
            'timeMin' => $from->format(\DateTimeInterface::RFC3339),
            'timeMax' => $to->format(\DateTimeInterface::RFC3339),
            'singleEvents' => true,
            'orderBy' => 'startTime',
        ]);

        return collect($events->getItems() ?? [])
            ->filter(fn (Event $event) => ! $this->isAutoGeneratedTaskEvent($event))
            ->map(fn (Event $event) => $this->mapEvent($event, $calendarId))
            ->values();
    }

    public function createEvent(
        GoogleConnection $connection,
        string $calendarId,
        string $summary,
        ?string $description,
        \DateTimeInterface $start,
        \DateTimeInterface $end,
        ?string $location = null
    ): array {
        $client = $this->clientFactory->buildClient($connection);
        $service = new Calendar($client);

        $event = new Event([
            'summary' => $summary,
            'description' => $description,
            'location' => $location,
            'start' => $this->eventDate($start),
            'end' => $this->eventDate($end),
        ]);

        $created = $service->events->insert($calendarId, $event);

        return $this->mapEvent($created, $calendarId);
    }

    public function updateEvent(
        GoogleConnection $connection,
        string $calendarId,
        string $eventId,
        array $payload
    ): array {
        $client = $this->clientFactory->buildClient($connection);
        $service = new Calendar($client);

        $existing = $service->events->get($calendarId, $eventId);

        if (array_key_exists('summary', $payload) && $payload['summary'] !== null && $payload['summary'] !== '') {
            $existing->setSummary($payload['summary']);
        }

        if (array_key_exists('description', $payload) && $payload['description'] !== null && $payload['description'] !== '') {
            $existing->setDescription($payload['description']);
        }

        if (array_key_exists('location', $payload) && $payload['location'] !== null && $payload['location'] !== '') {
            $existing->setLocation($payload['location']);
        }

        if (array_key_exists('start', $payload) && $payload['start'] instanceof \DateTimeInterface) {
            $existing->setStart($this->eventDate($payload['start']));
        }

        if (array_key_exists('end', $payload) && $payload['end'] instanceof \DateTimeInterface) {
            $existing->setEnd($this->eventDate($payload['end']));
        }

        $updated = $service->events->update($calendarId, $eventId, $existing);

        return $this->mapEvent($updated, $calendarId);
    }

    public function listCalendars(GoogleConnection $connection): Collection
    {
        $client = $this->clientFactory->buildClient($connection);
        $service = new Calendar($client);
        $calendars = $service->calendarList->listCalendarList();

        return collect($calendars->getItems() ?? [])
            ->map(fn (CalendarListEntry $calendar) => $this->mapCalendar($calendar))
            ->values();
    }

    private function mapEvent(Event $event, ?string $calendarId = null): array
    {
        return [
            'id' => $event->getId(),
            'summary' => $event->getSummary(),
            'description' => $event->getDescription(),
            'location' => $event->getLocation(),
            'start' => $event->getStart()?->getDateTime() ?? $event->getStart()?->getDate(),
            'end' => $event->getEnd()?->getDateTime() ?? $event->getEnd()?->getDate(),
            'calendar_id' => $calendarId,
        ];
    }

    private function mapCalendar(CalendarListEntry $calendar): array
    {
        $isPrimary = (bool) $calendar->getPrimary();

        return [
            'id' => $isPrimary ? 'primary' : $calendar->getId(),
            'name' => $calendar->getSummary(),
            'primary' => $isPrimary,
            'access_role' => $calendar->getAccessRole(),
        ];
    }

    private function isAutoGeneratedTaskEvent(Event $event): bool
    {
        $description = $event->getDescription();

        return is_string($description) && str_contains($description, 'https://tasks.google.com/task');
    }

    private function eventDate(\DateTimeInterface $dateTime): EventDateTime
    {
        return new EventDateTime([
            'dateTime' => $dateTime->format(\DateTimeInterface::RFC3339),
            'timeZone' => Config::get('app.timezone'),
        ]);
    }
}
